services:
  db:
    image: postgres:17
    container_name: bun-auth-postgres
    environment:
      POSTGRES_DB: estudaai_db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
